kind: Secret
apiVersion: v1
metadata:
  name: sentinel-mssql-db-secret
  namespace: default
data:
  # Password is P@ssword1$ so update it with password of your choice  
  SA_PASSWORD: MySentP@ssw0rd
type: Opaque
# ---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1beta1
# metadata:
#      name: azure-disk
# provisioner: kubernetes.io/azure-disk
# parameters:
#   storageaccounttype: Standard_LRS
#   kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sentinel-mssql-db-data
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sentinel-mssql-db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sentinel-mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentinel-mssql-db-secret
              key: SA_PASSWORD 
        volumeMounts:
        - name: sentinel-mssql
          mountPath: /var/opt/mssql
      volumes:
      - name: sentinel-mssql
        persistentVolumeClaim:
          claimName: sentinel-mssql-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-mssql-db-deployment
spec:
  selector:
    app: sentinel-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer