apiVersion: v1
kind: Service
metadata:
   name: {{ include "Sentinel.Api.Comms.fullname" . }}
   labels:
     app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
     helm.sh/chart: {{ include "Sentinel.Api.Comms.chart" . }}
     app.kubernetes.io/instance: {{ .Release.Name }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "Sentinel.Api.Comms.fullname" . }}
#   labels:
#     app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
#     helm.sh/chart: {{ include "Sentinel.Api.Comms.chart" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#     app.kubernetes.io/managed-by: {{ .Release.Service }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
