apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Util.Seq.fullname" . }}
  labels:
    {{- include "Sentinel.Util.Seq.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Util.Seq.service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "Sentinel.Util.Seq.selectorLabels" . | nindent 4 }}
