version: "3.4"

services:
  sentinel-api-scheduler-test:
    image: sentinel-api-scheduler-test
    build:
      target: test
      context: ../
      dockerfile: Sentinel.Api.Scheduler/dockerfile-linux-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
