apiVersion: v1
kind: Service
metadata:
  name: sentinel-util-mailhog
  labels:
    app: sentinel-util-mailhog
spec:
  type: LoadBalancer
  selector:
    app: sentinel-util-mailhog
  ports:                     
  - name: http               
    port: 8025               
    targetPort: 8025
    protocol: TCP            
  - name: transport          
    port: 1025               
    targetPort: 1025
    protocol: TCP
  # ports:
  # - protocol: TCP
  #   port: 1025
  #   targetPort: 1025
#---
# apiVersion: v1
# kind: Service
# metadata:
#   name: sentinel-util-mailhog-monitor
#   labels:
#     app: sentinel-util-mailhog
# spec:
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 8025
#     targetPort: 8025
#   selector:
#     app: sentinel-util-mailhog
# ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-util-mailhog
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: sentinel-util-mailhog
    spec:
      containers:
      - name: sentinel-util-mailhog
        image: mmercan/sentinel-util-mailhog
        ports:
        - containerPort: 1025
        - containerPort: 8025
