version: "3.4"

services:
  sentinel-jupyterdotnet:
    image: mmercan/sentinel-jupyterdotnet:latest
    build:
      # target: final
      context: ./
      dockerfile: Dockerfile
      args:
        buildtime_SONARKEY: __SONARKEY__
    ports:
      - "8888:8888"
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Production
    #   - DOTNET_USE_POLLING_FILE_WATCHER=1
    # # ports:
    # #   - "5005:80"
