{{- if .Values.ingress.enabled -}}
{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
{{- $fullName := include "Sentinel.Api.Member.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ $fullName }}
  labels:
    {{- include "Sentinel.Api.Member.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ $host }}
    secretName: "{{ $host }}-secret"
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path:  {{ $ingressPath }}
        backend:
          serviceName: {{ include "Sentinel.Api.Member.fullname" . }}
          servicePort: 80
{{- end }}