{{- $name := include "Sentinel.UI.Admin.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "Sentinel.UI.Admin.fullname" . }}
  labels:
    {{- include "Sentinel.UI.Admin.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.UI.Admin.annotations" . | nindent 4 }}
    taka/downscale-crontab : "0,30 * * * *"
    taka/downscale-replica : "0"
    taka/scale-timezone : "Australia/Melbourne"
    taka/upscale-crontab : "15,45 * * * *"
    taka/upscale-replica : "1"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "Sentinel.UI.Admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Sentinel.UI.Admin.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Sentinel.UI.Admin.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http 
          {{- if or .Values.configmap .Values.secrets }}
          envFrom:
          {{- end }}
          {{- if .Values.configmap }}
            - configMapRef:
                name: {{ $cfgname }}
          {{- end }}
          {{- if .Values.secrets }}   
            - secretRef:
                name: {{ $secretname }}
           {{- end }}
          env:
            - name: buildnumber
              value: {{ .Values.buildnumber | quote }}
            - name: branch
              value: {{  .Values.branch | quote }}
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}

