{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "Sentinel.UI.Admin.fullname" . }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.UI.Admin.name" . }}
    helm.sh/chart: {{ include "Sentinel.UI.Admin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: "Opaque"
data:
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}

{{- end }}
