apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-config"
data:
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value  | quote }}
{{- end -}}
{{- end }}
  elasticsearch.yml: |
{{ include (print .Template.BasePath "/_elasticsearch.yaml.tpl") . | indent 4 }}
  role_mapping.yml: |
