apiVersion: v1               
kind: Service                
metadata:                    
  name: {{ include "Sentinel.Db.Elasticsearch.fullname" . }}        
  labels:                    
    {{- include "Sentinel.Db.Elasticsearch.labels" . | nindent 4 }}
spec:                        
  type:  {{ .Values.service.type }}
  selector:
    {{- include "Sentinel.Db.Elasticsearch.selectorLabels" . | nindent 4 }}
  ports:                     
  - name: http               
    port: 80               
    targetPort: 9200
    protocol: TCP            
  - name: transport          
    port: 9300               
    targetPort: 9300
    protocol: TCP
    