apiVersion: v1               
kind: Service                
metadata:                    
  name: {{ include "Sentinel.Db.Elasticsearch.fullname" . }}        
  labels:                    
    app.kubernetes.io/name: {{ include "Sentinel.Db.Elasticsearch.name" . }}
    helm.sh/chart: {{ include "Sentinel.Db.Elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:                        
  type:  {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Db.Elasticsearch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:                     
  - name: http               
    port: 80               
    targetPort: 9200
    protocol: TCP            
  - name: transport          
    port: 9300               
    targetPort: 9300
    protocol: TCP
    