
{{- $name := include "Sentinel.Db.Elasticsearch.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "Sentinel.Db.Elasticsearch.fullname" . }}
  labels:
    {{- include "Sentinel.Db.Elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Db.Elasticsearch.annotations" . | nindent 4 }}
spec:
  serviceName: {{ include "Sentinel.Db.Elasticsearch.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "Sentinel.Db.Elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Sentinel.Db.Elasticsearch.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Sentinel.Db.Elasticsearch.annotations" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 15
      initContainers:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        envFrom:
          {{ if .Values.secrets -}}
          - secretRef:
              name: {{ $secretname }}
          {{- end }}
        env:
          - name: cluster.name
            value: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-cluster"
          - name: CLUSTER_NAME
            value: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-cluster"
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end -}}
          {{- end }}
        volumeMounts:
        - name: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-volume"
          mountPath: /usr/share/elasticsearch/data
        - name: {{ $cfgname }}
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: {{ $cfgname }}
          mountPath: /usr/share/elasticsearch/config/role_mapping.yml
          subPath: role_mapping.yml
      volumes:
      - name: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-volume"
        persistentVolumeClaim:
           claimName: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-data"
      - name: {{ $cfgname }}
        configMap:
            name: {{ $cfgname }}
