apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "Sentinel.Db.Elasticsearch.fullname" . }}-data"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 8Gi
