    version: '3.4'

    services:
      sentinel-ui-admin:      
        image: mmercan/sentinel-ui-admin:${TAGVersion}-prod-linux
        build:
          target: prod
          context: ../
          dockerfile: Sentinel.UI.Admin/dockerfile
        # environment:
        #   - ASPNETCORE_ENVIRONMENT=Production
        #   - DOTNET_USE_POLLING_FILE_WATCHER=1
        # ports:
        #   - "5005:80"