version: '3.4'

services:
  # sentinel-ui-product:      
  #   environment:
  #     - sentinel-ui-sts__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
  #     - sentinel-api-member__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
  #     - sentinel-api-product__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
  #     - sentinel-api-comms__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
  sentinel-api-product:      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sentinel-api-member:      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sentinel-api-comms:      
    environment:
      - NATS_URL=nats://sentinel-service-nats:4222/
  sentinel-handler-comms:      
    environment:
      - RabbitMQConnection=host=sentinel-service-rabbitmq;username=rabbitmq;password=rabbitmq; timeout=10
      - NATS_URL=nats://sentinel-service-nats:4222/
  sentinel-handler-product:      
    environment:
      - RabbitMQConnection=host=sentinel-service-rabbitmq;username=rabbitmq;password=rabbitmq; timeout=10
  sentinel-ui-sts:      
    environment:
      - sentinel-ui-sts__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
      - sentinel-api-member__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
      - sentinel-api-product__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
      - sentinel-api-comms__ClientOptions__ClientSecret=mvcwhjfpDRQT4FYz2Hzg9xOcUchbtr1xWIXZbMjLLps=
  sentinel-ui-admin:      
     environment:
      - test=host=yes
  sentinel-elk-proxy:      
    environment:
      - test=host=yes
  sentinel-db-redis:
    environment:
      - test=host=yes
  sentinel-db-elasticsearch:
    environment:
      - test=host=yes
  sentinel-db-mongodb:
    environment:
      - MONGO_DATA_DIR=/data/db
  sentinel-db-mysql:
    environment:
      - test=host=yes
  sentinel-service-nats:
    environment:
      - test=host=yes
  sentinel-service-rabbitmq:
    environment:
       RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  sentinel-util-mailhog:
    environment:
      - test=host=yes
  sentinel-util-kibana:
    environment:
      - ELASTICSEARCH_URL=http://40.117.115.1:9200
  sentinel-elk-logstash:
    environment:
      - ELASTICSEARCH_URL=http://sentinel-db-elasticsearch:9200
  sentinel-util-phpmyadmin:
    environment:
      - test=host=yes
  sentinel-ui-wordpress:      
    environment:
      - test=host=yes
  sentinel-ui-orchard:      
    environment:
      - test=host=yes
  sentinel-ml-tensorflow:
    environment:
      - test=host=yes
