version: '3.4'

services:
  sentinel-db-elasticsearch:
    image: mmercan/sentinel-db-elasticsearch:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Db.Elasticsearch
      dockerfile: dockerfile-linux
    ports:
      - "9200:9200"
      - "9300:9300"
  sentinel-util-kibana:
    image: mmercan/sentinel-util-kibana:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Util.Kibana
      dockerfile: dockerfile-linux
    environment:
      - ELASTICSEARCH_URL=http://sentinel-db-elasticsearch:9200
    ports:
      - "5601:5601"