FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base
ENV ASPNETCORE_URLS=http://+:80
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS develop
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.Api.Comms
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.Api.Comms/Sentinel.Api.Comms.csproj Sentinel.Api.Comms/
RUN dotnet restore Sentinel.Api.Comms/Sentinel.Api.Comms.csproj
COPY . .
WORKDIR /src/Sentinel.Api.Comms
RUN dotnet build Sentinel.Api.Comms.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.Api.Comms.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.Api.Comms.dll"]
