FROM mmercan/sentinel-sonarqube-dotnet22-sdk AS test
ARG buildtime_APPID
ARG buildtime_APPSECRET
ARG buildtime_ADID
# ENV DOTNET_USE_POLLING_FILE_WATCHER=1
# ENV ASPNETCORE_ENVIRONMENT=Development
# ENV SONAR_HOST http://sonar.myrcan.com
# RUN apt-get update && apt-get install -y openjdk-8-jdk
# RUN dotnet tool install --global dotnet-sonarscanner
# ENV PATH="${PATH}:/root/.dotnet/tools"
ENV PROJECT=Sentinel.Api.Product
ENV VERSION=1.0
ENV SONARKEY=291e97953a3742b000a056732d73dce5ef439985
ENV APPID=$buildtime_APPID
ENV APPSECRET=$buildtime_APPSECRET
ENV ADID=$buildtime_ADID
ENV SentinelConnection="Server=52.247.221.7;Database=sentinel;User Id=sa;Password=MySentP@ssw0rd;"
ENV RedisConnection="sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword"
ENV Mongodb__ConnectionString="mongodb://root:hbMnztmZ4w9JJTGZ@52.247.221.171:27017/admin?readPreference=primary"
ENV Mongodb__DatabaseName=sentinel
ENV Mongodb__CollectionName=product
ENV Mongodb__IdField=Id


WORKDIR /src
COPY Sentinel.Api.Product/Sentinel.Api.Product.csproj Sentinel.Api.Product/
RUN dotnet restore Sentinel.Api.Product/Sentinel.Api.Product.csproj
COPY . .
RUN dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONARKEY  /d:sonar.cs.opencover.reportsPaths="/TestResults/coverage.opencover.xml" /d:sonar.exclusions="**bootstrap.css, **bootstrap.js" /d:sonar.coverage.exclusions="**Tests*.cs"
RUN dotnet build ./Sentinel.Api.Product/Sentinel.Api.Product.sln
RUN dotnet test ./Sentinel.Api.Product/Sentinel.Api.Product.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/
RUN dotnet build-server shutdown
RUN dotnet sonarscanner end /d:sonar.login=$SONARKEY