{{- if .Values.istio.enabled -}}
{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "Sentinel.Api.Billing.fullname" . }}-vs
spec:
  hosts:
    - {{ $host }}
  gateways:
    - {{ include "Sentinel.Api.Billing.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "Sentinel.Api.Billing.fullname" . }}  # Service Name
            port:
              number: {{ .Values.service.port }}

{{- end }}