FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS develop
# RUN apt-get update && apt-get install bash
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.UI.Product
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.UI.Product/Sentinel.UI.Product.csproj Sentinel.UI.Product/
RUN dotnet restore Sentinel.UI.Product/Sentinel.UI.Product.csproj
COPY . .
WORKDIR /src/Sentinel.UI.Product
RUN dotnet build Sentinel.UI.Product.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.UI.Product.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.UI.Product.dll"]
