apiVersion: v1
kind: Service
metadata:
  name: sentinel-util-zookeeper
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
  selector:
    app: sentinel-util-zookeeper
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-util-zookeeper-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-util-zookeeper
    spec:
      containers:
      - name: sentinel-util-zookeeper
        image: mmercan/sentinel-util-zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-util-kafka
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  selector:
    app: sentinel-util-kafka
---
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-util-kafka-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-util-kafka
    spec:
      containers:
      - name: sentinel-util-kafka
        image: mmercan/sentinel-util-kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "sentinel-util-zookeeper:2181/local"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "sentinel-util-kafka"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1"
---
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-util-kafka-manager
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  selector:
    app: sentinel-util-kafka-manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-util-kafka-manager-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-util-kafka-manager
    spec:
      containers:
      - name: sentinel-util-kafka-manager
        image: mmercan/sentinel-util-kafka-manager
        ports:
        - containerPort: 9000
---