{{- $name := include "Sentinel.Service.Rabbitmq.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  {{ include "Sentinel.Service.Rabbitmq.fullname" . }}
  labels:
    {{- include "Sentinel.Service.Rabbitmq.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Service.Rabbitmq.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "Sentinel.Service.Rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Sentinel.Service.Rabbitmq.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Sentinel.Service.Rabbitmq.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "Sentinel.Service.Rabbitmq.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - configMapRef:
                name: {{ $cfgname }}
            - secretRef:
                name: {{ $secretname }}
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}
