apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "Sentinel.Service.Rabbitmq.fullname" . }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "Sentinel.Service.Rabbitmq.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Service.Rabbitmq.annotations" . | nindent 4 }}
type: "Opaque"
data:
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}