apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Service.Rabbitmq.fullname" . }}-tcp
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Service.Rabbitmq.name" . }}-tcp
    helm.sh/chart: {{ include "Sentinel.Service.Rabbitmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:        
  - name: transport          
    port: 5672               
    targetPort: 5672
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Service.Rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

