apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Service.Rabbitmq.fullname" . }}-http
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Service.Rabbitmq.name" . }}-http
    helm.sh/chart: {{ include "Sentinel.Service.Rabbitmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http               
    port: 80               
    targetPort: 15672
    protocol: TCP            
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Service.Rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

