apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Db.Mongodb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Db.Mongodb.name" . }}
    helm.sh/chart: {{ include "Sentinel.Db.Mongodb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Db.Mongodb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

