apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: px-mongo-pvc
  #  annotations:
  #    volume.beta.kubernetes.io/storage-class: azurefile
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi