FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base
ENV ASPNETCORE_URLS=http://+:80
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS develop
# RUN apt-get update && apt-get install bash
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.Api.HealthMonitoring
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.Api.HealthMonitoring/Sentinel.Api.HealthMonitoring.csproj Sentinel.Api.HealthMonitoring/
RUN dotnet restore Sentinel.Api.HealthMonitoring/Sentinel.Api.HealthMonitoring.csproj
COPY . .
WORKDIR /src/Sentinel.Api.HealthMonitoring
RUN dotnet build Sentinel.Api.HealthMonitoring.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.Api.HealthMonitoring.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.Api.HealthMonitoring.dll"]
