
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "Sentinel.UI.HealthMonitoring.fullname" . }}-config"
data:
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value  | quote }}
{{- end -}}
{{- end }}
  config.json: |
{{ include (print .Template.BasePath "/_health.json.tpl") . | indent 4 }}

