{{- $name := include "Sentinel.UI.HealthMonitoring.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $cfghealthcheck := printf "%s-%s" $name "cfghealthcheck" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  {{ include "Sentinel.UI.HealthMonitoring.fullname" . }}
  labels:
    {{- include "Sentinel.UI.HealthMonitoring.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.UI.HealthMonitoring.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "Sentinel.UI.HealthMonitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Sentinel.UI.HealthMonitoring.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Sentinel.UI.HealthMonitoring.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "Sentinel.UI.HealthMonitoring.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http 
          {{- if or .Values.configmap .Values.secrets }}
          envFrom:
          {{- end }}
          {{- if .Values.secrets }}   
            - secretRef:
                name: {{ $secretname }}
           {{- end }}
          env:
            - name: buildnumber
              value: {{ .Values.buildnumber | quote }}
            - name: branch
              value: {{  .Values.branch | quote }}
          {{- if .Values.envvalues -}}
          {{- range $key, $value := .Values.envvalues }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end -}}
          {{- end }}
          volumeMounts:
            - name: {{ $cfgname }}
              mountPath: /usr/share/nginx/html/assets/config/config.json
              subPath: config.json
            - name: {{ $cfghealthcheck }}
              mountPath: /usr/share/nginx/html/assets/config/healthcheck.json
              subPath: healthcheck.json
      volumes:
      - name: {{ $cfgname }}
        configMap:
          name: {{ $cfgname }}
      - name: {{ $cfghealthcheck }}
        configMap:
          name: {{ $cfghealthcheck }}
