version: '3.4'

services:
  sentinel-db-redis:
    image: mmercan/sentinel-db-sql:${TAGVersion}-prod-linux
    build:
      context: ./
      dockerfile: dockerfile-linux
    # volumes:
    #   - C:\repos\sentinel\Sentinel.Web\Sentinel.Db.Redis:/data   
    # command: redis-server --requirepass yourpassword
    # command: ["redis-server", "--appendonly", "yes"]
    hostname: sql
    ports:
      - "1433:1433"
