apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Api.Scheduler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Scheduler.name" . }}
    helm.sh/chart: {{ include "Sentinel.Api.Scheduler.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- include "Sentinel.Api.Scheduler.service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Scheduler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
