FROM nginx
EXPOSE 8080 9200
RUN apt-get update -y \
    && apt-get install -y \
    apache2-utils \
    && rm -rf /var/lib/apt/lists/*


ENV USER=mercan
ENV PASS=Password123

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./auth.htpasswd /etc/nginx/auth.htpasswd
RUN htpasswd -c -b /etc/nginx/auth.htpasswd $USER $PASS

# COPY ./auth.conf /etc/nginx/conf.d/auth.conf

# ENV FORWARD_PORT=80
# WORKDIR /opt
# #RUN apk add --no-cache gettext

# RUN chmod 0755 ./launch.sh
# CMD ["./launch.sh"]


# FROM nginx:alpine as prod
# EXPOSE 80
# COPY ./auth /etc/nginx/conf.d

# WORKDIR /usr/share/nginx/html
# COPY --from=builder /home/node/admin/dist/ClientApp/ .