apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-api-comms-helm
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: sentinel-api-comms-helm
    spec:
      containers:
      - name:  sentinel-api-comms-helm
        image: mmercan/sentinel-api-comms:__imageversion__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: ASPNETCORE_ENVIRONMENT
        - name: RedisConnection
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: RedisConnection
        - name: Mongodb__ConnectionString
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: Mongodb__ConnectionString
        - name: Mongodb__DatabaseName
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: Mongodb__DatabaseName
        - name: Mongodb__CollectionName
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: Mongodb__CollectionName
        - name: Mongodb__IdField
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: Mongodb__IdField
        - name: SentinelConnection
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: SentinelConnection
        - name: kafkaUrl
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: kafkaUrl
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: NATS_URL
        - name: MongoConnection
          valueFrom:
            configMapKeyRef:
              name: sentinel-api-comms-config
              key: MongoConnection
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
