apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-api-comms-helm
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: sentinel-api-comms-helm
    spec:
      containers:
      - name:  sentinel-api-comms-helm
        image: mmercan/sentinel-api-comms:__imageversion__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RedisConnection
          value: "sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword"
        - name: Mongodb__ConnectionString
          value: "mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary"
        - name: Mongodb__DatabaseName
          value: "sentinel"
        - name: Mongodb__CollectionName
          value: "product"
        - name: Mongodb__IdField
          value: "Id"
        - name: SentinelConnection
          value: "Server=sentinel-mssql-db;Database=sentinel;User Id=sa;Password=MySentP@ssw0rd;"
        - name: kafkaUrl
          value: "http://sentinel-util-kafka:9092"
        - name: NATS_URL
          value: "nats://sentinel-service-nats:4222/"
        - name: MongoConnection
          value: "mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary"
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
