apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "Sentinel.Api.Comms.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
    helm.sh/chart: {{ include "Sentinel.Api.Comms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RedisConnection
          value: "sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword"
        - name: Mongodb__ConnectionString
          value: "mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary"
        - name: Mongodb__DatabaseName
          value: "sentinel"
        - name: Mongodb__CollectionName
          value: "product"
        - name: Mongodb__IdField
          value: "Id"
        - name: SentinelConnection
          value: "Server=sentinel-mssql-db;Database=sentinel;User Id=sa;Password=MySentP@ssw0rd;"
        - name: kafkaUrl
          value: "http://sentinel-util-kafka:9092"
        - name: NATS_URL
          value: "nats://sentinel-service-nats:4222/"
        - name: MongoConnection
          value: "mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary"
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
# apiVersion: apps/v1beta2
# kind: Deployment
# metadata:
#   name: {{ include "Sentinel.Api.Comms.fullname" . }}
#   labels:
#     app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
#     helm.sh/chart: {{ include "Sentinel.Api.Comms.chart" . }}
#     app.kubernetes.io/instance: {{ .Release.Name }}
#     app.kubernetes.io/managed-by: {{ .Release.Service }}
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
#       app.kubernetes.io/instance: {{ .Release.Name }}
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
#         app.kubernetes.io/instance: {{ .Release.Name }}
#     spec:
#       containers:
#         - name: {{ .Chart.Name }}
#           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#           imagePullPolicy: {{ .Values.image.pullPolicy }}
#           ports:
#             - name: http
#               containerPort: 80
#               protocol: TCP
#           livenessProbe:
#             httpGet:
#               path: /
#               port: http
#           readinessProbe:
#             httpGet:
#               path: /
#               port: http
#           resources:
# {{ toYaml .Values.resources | indent 12 }}
#     {{- with .Values.nodeSelector }}
#       nodeSelector:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.tolerations }}
#       tolerations:
# {{ toYaml . | indent 8 }}
#     {{- end }}
