apiVersion: v1
kind: Service
metadata:
  name: sentinel-api-comms
  labels:
    app: sentinel-api-comms
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: sentinel-api-comms