apiVersion: v1
kind: Service
metadata:
  name: sentinel-api-comms-helm
  labels:
    app: sentinel-api-comms-helm
spec:
  type: {{ .Values.service.type }}
  ports:
  - port:  {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: sentinel-api-comms-helm
