version: '3.4'

services:
  sentinel-service-nats:
    image: mmercan/sentinel-service-nats:${TAGVersion}-prod-linux
    build:
      context: ./
      dockerfile: dockerfile-linux
    ports:
      - "8888:8888"
      - "6006:6006"

