    version: '3.4'

    services:
      sentinel-healthchecks:      
        image: mmercan/sentinel-healthchecks:${TAGVersion}-prod-linux
        build:
          target: test
          context: ../
          dockerfile: HealthChecks/dockerfile-linux-test
          args:
            buildtime_SONARKEY: fbf6f7c2fed68cbdc15fa82e269f973930831e3b
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - DOTNET_USE_POLLING_FILE_WATCHER=1
        volumes:
          - /opt/vsts/work/_temp:/TestResults
