FROM mmercan/sentinel-sonarqube-dotnet22-sdk AS test
ARG buildtime_APPID
ARG buildtime_APPSECRET
ARG buildtime_ADID
ARG buildtime_SONARKEY
# ENV DOTNET_USE_POLLING_FILE_WATCHER=1
# ENV ASPNETCORE_ENVIRONMENT=Development
# ENV SONAR_HOST http://sonar.myrcan.com
# RUN apt-get update && apt-get install -y openjdk-8-jdk
# ENV PROJECT sentinel-comms
# RUN dotnet tool install --global dotnet-sonarscanner
# ENV PATH="${PATH}:/root/.dotnet/tools"
ENV PROJECT=Sentinel.HealthChecks
ENV VERSION=1.0
ENV SONARKEY=$buildtime_SONARKEY
ENV APPID=$buildtime_APPID
ENV APPSECRET=$buildtime_APPSECRET
ENV ADID=$buildtime_ADID
ENV SentinelConnection="Server=52.247.221.7;Database=sentinel;User Id=sa;Password=MySentP@ssw0rd;"


WORKDIR /src
# COPY Sentinel.Api.Comms/Sentinel.Api.Comms.csproj Sentinel.Api.Comms/
# RUN dotnet restore Sentinel.Api.Comms/Sentinel.Api.Comms.csproj
COPY . .
RUN dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONARKEY  /d:sonar.cs.opencover.reportsPaths="/TestResults/" /d:sonar.exclusions="**bootstrap.css, **bootstrap-reboot.css, **bootstrap.js, **/wwwroot/**" /d:sonar.coverage.exclusions="**Tests*.cs"
RUN dotnet build ./HealthChecks/HealthChecks.sln

RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Common.Tests/Mercan.HealthChecks.Common.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.Common.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Elasticsearch.Tests/Mercan.HealthChecks.Elasticsearch.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.Elasticsearch.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Mongo.Tests/Mercan.HealthChecks.Mongo.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.Mongo.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.MySql.Tests/Mercan.HealthChecks.MySql.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.MySql.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Nats.Tests/Mercan.HealthChecks.Nats.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.Nats.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Network.Tests/Mercan.HealthChecks.Network.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.Network.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.RabbitMQ.Tests/Mercan.HealthChecks.RabbitMQ.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.RabbitMQ.Tests.xml
RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Redis.Tests/Mercan.HealthChecks.Redis.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/HealthChecks.Redis.Tests.xml

# RUN dotnet test ./HealthChecks/Mercan.HealthChecks.Common.Tests/Mercan.HealthChecks.Common.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/Mercan.HealthChecks.Common.Tests.xml
# RUN dotnet test ./Sentinel.Api.Comms.Tests/Sentinel.Api.Comms.Tests.csproj /p:CollectCoverage=true  /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/Sentinel.Api.Comms.Tests.xml 
RUN dotnet build-server shutdown
RUN dotnet sonarscanner end /d:sonar.login=$SONARKEY