FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.2
EXPOSE 9200 9300

# FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.0
# COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/

