    version: '3.4'

    services:
      sentinel-ui-sts:      
        image: mmercan/sentinel-ui-sts:${TAGVersion}-prod-linux
        build:
          target: final
          context: ../
          dockerfile: Sentinel.UI.STS/dockerfile-linux
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - DOTNET_USE_POLLING_FILE_WATCHER=1
        # ports:
        #   - "5005:80"