FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS develop
# RUN apt-get update && apt-get install bash
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.UI.STS
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.UI.STS/Sentinel.UI.Sts.csproj Sentinel.UI.STS/
RUN dotnet restore Sentinel.UI.STS/Sentinel.UI.Sts.csproj
COPY . .
WORKDIR /src/Sentinel.UI.STS
RUN dotnet build Sentinel.UI.Sts.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.UI.Sts.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.UI.Sts.dll"]
