FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS develop
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.UI.STS
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.UI.STS/Sentinel.UI.STS.csproj Sentinel.UI.STS/
RUN dotnet restore Sentinel.UI.STS/Sentinel.UI.STS.csproj
COPY . .
WORKDIR /src/Sentinel.UI.STS
RUN dotnet build Sentinel.UI.STS.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.UI.STS.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.UI.STS.dll"]
