{{- $name := include "Sentinel.Db.Redis.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "Sentinel.Db.Redis.fullname" . }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Db.Redis.name" . }}
    helm.sh/chart: {{ include "Sentinel.Db.Redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: "Opaque"
data:
 RedisConnection:  {{ printf "%s:6379,defaultDatabase=2,password=%s" $name .Values.password | b64enc | quote }}
 {{- if .Values.secrets -}}
{{- range $key, $value := .Values.secrets }}
 {{ $key }}: {{ default "" $value | b64enc | quote }}
{{- end -}}
{{- end }}