apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Db.Redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Db.Redis.name" . }}
    helm.sh/chart: {{ include "Sentinel.Db.Redis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "Sentinel.Db.Redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

