apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "Sentinel.Util.Kibana.fullname" . }}-config"
data:
  kibana.yml: |
    server.name: sentinel-elk-kibana
    server.host: "0"
    elasticsearch.url: http://sentinel-db-elasticsearch.sentinel-helm:9200
    elasticsearch.hosts: ["http://sentinel-db-elasticsearch.sentinel-helm:9200"]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: elastic
    elasticsearch.password: Pa$$w0rd

