{{- $name := include "Sentinel.Util.Kibana.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  {{ include "Sentinel.Util.Kibana.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Util.Kibana.name" . }}
    helm.sh/chart: {{ include "Sentinel.Util.Kibana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version:  {{ .Chart.AppVersion }}
    branch:  {{ .Values.branch }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "Sentinel.Util.Kibana.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "Sentinel.Util.Kibana.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        branch:  {{ .Values.branch }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http 
          volumeMounts:
          - name: "{{ include "Sentinel.Util.Kibana.fullname" . }}-volume"
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}
      volumes:
      - name: "{{ include "Sentinel.Util.Kibana.fullname" . }}-volume"
        configMap:
            name: "{{ include "Sentinel.Util.Kibana.fullname" . }}-config"

