{{- $name := include "Sentinel.Util.Kibana.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "Sentinel.Util.Kibana.fullname" . }}
  labels:
    {{- include "Sentinel.Util.Kibana.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Util.Kibana.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "Sentinel.Util.Kibana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Sentinel.Util.Kibana.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Sentinel.Util.Kibana.annotations" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end }}
          volumeMounts:
            - name: {{ $cfgname }}
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
      volumes:
      - name: {{ $cfgname }}
        configMap:
            name: {{ $cfgname }}

