FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80


FROM microsoft/dotnet:2.2-sdk AS develop
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.Api.Billing
EXPOSE 80


FROM develop AS build
WORKDIR /src
COPY Sentinel.Api.Billing/Sentinel.Api.Billing.csproj Sentinel.Api.Billing/
RUN dotnet restore Sentinel.Api.Billing/Sentinel.Api.Billing.csproj
COPY . .
WORKDIR /src/Sentinel.Api.Billing
RUN dotnet build Sentinel.Api.Billing.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.Api.Billing.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.Api.Billing.dll"]
