apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "Sentinel.Api.Product.fullname" . }}-config"
data:
 {{- if .Values.configmap -}}
{{- range $key, $value := .Values.configmap }}
 {{ $key }}: {{ default "" $value  | quote }}
{{- end -}}
{{- end }}


