{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ include "Sentinel.Api.Product.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Product.name" . }}
    helm.sh/chart: {{ include "Sentinel.Api.Product.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ $host }}
    secretName: tls-secret-product-helm-prod
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "Sentinel.Api.Product.fullname" . }}
          servicePort: 80