{{- if .Values.ingress.enabled -}}
{{- $host := printf "%s.%s.%s" .Chart.Name .Values.environment .Values.hostdomain -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ include "Sentinel.Api.Product.fullname" . }}
  labels:
    {{- include "Sentinel.Api.Product.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ $host }}
    secretName: "{{ $host }}-secret"
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "Sentinel.Api.Product.fullname" . }}
          servicePort: 80
{{- end }}