version: '3.4'

services:
  sentinel-api-product:      
    image: mmercan/sentinel-api-product:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Api.Product/dockerfile-linux
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - Mongodb__ConnectionString=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - Mongodb__DatabaseName=sentinel
      - Mongodb__CollectionName=product
      - Mongodb__IdField=Id
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5003:80"
    depends_on:
      - sentinel-db-redis
  sentinel-api-comms:      
    image: mmercan/sentinel-api-comms:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Api.Comms/dockerfile-linux
    environment:
      - NATS_URL=nats://sentinel-service-nats:4222/
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - MongoConnection=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5004:80"
    depends_on:
      - sentinel-db-redis
  sentinel-web-sts:      
    image: mmercan/sentinel-web-sts:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Web.STS/dockerfile-linux
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - MongoConnection=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - SMTP__Server=sentinel-util-mailhog
      - SMTP__Port=1025
      - SMTP__UserName=mail@mail.com
      - SMTP__Password=password123
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5000:80"
  sentinel-api-member:      
    image: mmercan/sentinel-api-member:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Api.Member/dockerfile-linux
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - Mongodb__ConnectionString=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - Mongodb__DatabaseName=sentinel
      - Mongodb__CollectionName=product
      - Mongodb__IdField=Id
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5002:80"
    depends_on:
      - sentinel-db-redis
  sentinel-web-admin:      
    image: mmercan/sentinel-web-admin:${TAGVersion}-prod-linux
    build:
      target: prod
      context: .
      dockerfile: Sentinel.Web.Admin/dockerfile
    ports:
      - "80:80"
  sentinel-elk-proxy:      
    image: mmercan/sentinel-elk-proxy:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.elk.Proxy
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "9200:9200" 
  sentinel-db-redis:
    image: mmercan/sentinel-db-redis:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Db.Redis
      dockerfile: dockerfile
    # volumes:
    #   - C:\repos\sentinel\Sentinel.Web\Sentinel.Db.Redis:/data   
    # command: redis-server --requirepass yourpassword
    # command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
  sentinel-db-mongodb:
    image: mmercan/sentinel-db-mongodb:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Db.Mongodb
      dockerfile: dockerfile-linux
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hbMnztmZ4w9JJTGZ
    # volumes:
    #   - ./data/db:/data/db
    ports:
        - 27017:27017
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
  sentinel-service-nats:
    image: mmercan/sentinel-service-nats:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Service.Nats
      dockerfile: dockerfile-linux
    ports:
      - "8222:8222"
      - "4222:4222"
  sentinel-service-rabbitmq:
    image: mmercan/sentinel-service-rabbitmq:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Service.Rabbitmq
      dockerfile: dockerfile-linux
    labels:
      NAME: "rabbitmq1"
    environment:
       RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      #   RABBITMQ_DEFAULT_USER: "rabbitmq"
      #   RABBITMQ_DEFAULT_PASS: "rabbitmq"
      #   RABBITMQ_DEFAULT_VHOST: "/"
    # volumes:
      # - ./config/:/etc/rabbitmq/
      # - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      # - "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
    ports:
    - "15672:15672"
    - "5672:5672"
  sentinel-util-mailhog:
    image: mmercan/sentinel-util-mailhog:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Util.Mailhog
      dockerfile: dockerfile-linux
    ports:
      - "1025:1025"
      - "8025:8025"
  sentinel-elk-logstash:
    image: mmercan/sentinel-elk-logstash:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.elk.Logstash
      dockerfile: dockerfile-linux
    environment:
      - ELASTICSEARCH_URL=http://sentinel-db-elasticsearch:9200
    ports:
      - "5044:5044"
      - "9600:9600"
  sentinel-util-zookeeper:
    image: mmercan/sentinel-util-zookeeper:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Util.Kafka
      dockerfile: dockerfile-zookeeper
    ports:
      - 2181:2181
  sentinel-util-kafka:
    image: mmercan/sentinel-util-kafka:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Util.Kafka
      dockerfile: dockerfile-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: sentinel-util-zookeeper:2181/local
      KAFKA_ADVERTISED_HOST_NAME: sentinel-util-kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1"
  sentinel-util-kafka-manager:
    image: mmercan/sentinel-util-kafka-manager:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Util.Kafka
      dockerfile: dockerfile-manager
    ports:
      - 9000:9000
  # sqldb:
  #   image: mmercan/sentinel-sql-db:${TAGVersion}-prod-linux
  #   build:
  #     context: ./Sentinel.Db.Sql/
  #     dockerfile: dockerfile-linux
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "Sentinel2018"
  #     ACCEPT_EULA: "Y"
  #   healthcheck:
  #     test: sqlcmd -S sqldb -U SA -P 'Sentinel2018' -Q 'select 1'
  #   # networks:
  #   #   mynetwork:
  #   #     aliases:
  #   #       - db1.internal.prod.example.com
# networks:
#   default:
#     external:
#       name: nat

# volumes:
#   Sentinel2018Web:
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       #device: 'C:\repos\sentinel\Sentinel.Web'
#       device: '/c/repos/sentinel/sentinel.web'
