version: '3.4'

services:
  sentinel-web-api-product:      
    image: mmercan/sentinel-web-api-product:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Web.Api.Product/dockerfile-linux
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - Mongodb__ConnectionString=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - Mongodb__DatabaseName=sentinel
      - Mongodb__CollectionName=product
      - Mongodb__IdField=Id
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5003:80"
    depends_on:
      - sentinel-db-redis
  sentinel-web-api-comms:      
    image: mmercan/sentinel-web-api-comms:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Web.Api.Comms/dockerfile-linux
    environment:
      - NATS_URL=nats://sentinel-nats:4222/
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - MongoConnection=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5004:80"
    depends_on:
      - sentinel-db-redis
  sentinel-web-sts:      
    image: mmercan/sentinel-web-sts:${TAGVersion}-prod-linux
    build:
      target: final
      context: .
      dockerfile: Sentinel.Web.STS/dockerfile-linux
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RedisConnection=sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword
      - MongoConnection=mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - SMTP__Server=sentinel-util-mailhog
      - SMTP__Port=1025
      - SMTP__UserName=mail@mail.com
      - SMTP__Password=password123
      - SentinelConnection=Server=sqldb;Database=sentinel;User Id=sa;Password=Sentinel2018;
    ports:
      - "5000:80"
    #depends_on:
    #  - sqldb
  sentinel-web-admin:      
    image: mmercan/sentinel-web-admin:${TAGVersion}-prod-linux
    build:
      target: prod
      context: .
      dockerfile: Sentinel.Web.Admin/dockerfile
    ports:
      - "80:80"
  # sqldb:
  #   image: mmercan/sentinel-sql-db:${TAGVersion}-prod-linux
  #   build:
  #     context: ./Sentinel.Sql.Db/
  #     dockerfile: dockerfile-linux
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "Sentinel2018"
  #     ACCEPT_EULA: "Y"
  #   healthcheck:
  #     test: sqlcmd -S sqldb -U SA -P 'Sentinel2018' -Q 'select 1'
  #   # networks:
  #   #   mynetwork:
  #   #     aliases:
  #   #       - db1.internal.prod.example.com
  sentinel-db-redis:
    image: mmercan/sentinel-db-redis:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Db.Redis
      dockerfile: dockerfile
    # volumes:
    #   - C:\repos\sentinel\Sentinel.Web\Sentinel.Db.Redis:/data   
    # command: redis-server --requirepass yourpassword
    # command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
  sentinel-db-elasticsearch:
    image: mmercan/sentinel-db-elasticsearch:${TAGVersion}-dev-linux
    build:
      context: ./Sentinel.Db.Elasticsearch
      dockerfile: dockerfile-linux
    ports:
      - "9200:9200"
      - "9300:9300"
  sentinel-db-mongodb:
    image: mmercan/sentinel-db-mongodb:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Db.Mongodb
      dockerfile: dockerfile-linux
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hbMnztmZ4w9JJTGZ
    # volumes:
    #   - ./data/db:/data/db
    ports:
        - 27017:27017
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
  sentinel-nats:
    image: mmercan/sentinel-nats:${TAGVersion}-prod-linux
    build:
      context: ./sentinel-nats
      dockerfile: dockerfile-linux
    ports:
      - "8222:8222"
      - "4222:4222"
  sentinel-util-mailhog:
    image: mmercan/sentinel-util-mailhog:${TAGVersion}-prod-linux
    build:
      context: ./Sentinel.Util.Mailhog
      dockerfile: dockerfile-linux
    ports:
      - "1025:1025"
      - "8025:8025"
 
# networks:
#   default:
#     external:
#       name: nat

# volumes:
#   Sentinel2018Web:
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       #device: 'C:\repos\sentinel\Sentinel.Web'
#       device: '/c/repos/sentinel/sentinel.web'
