apiVersion: v1
kind: Service
metadata:
  name: sentinel-web-admin
  labels:
    run: sentinel-web-admin
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    run: sentinel-web-admin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-web-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-web-admin
    spec:
      containers:
      - name: sentinel-web-admin
        image: mmercan/sentinel-web-admin
        ports:
        - containerPort: 80    