apiVersion: v1
kind: Service
metadata:
  name: sentinel-web-admin
  labels:
    app: sentinel-web-admin
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: sentinel-web-admin

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-web-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-web-admin
    spec:
      containers:
      - name: sentinel-web-admin
        image: mmercan/sentinel-web-admin
        ports:
        - containerPort: 80   

#---
#STS
#---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-web-sts-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: sentinel-web-sts

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-web-sts-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-web-sts
    spec:
      containers:
      - name: sentinel-web-sts
        image: mmercan/sentinel-web-sts
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RedisConnection
          value: "sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword"
        - name: Mongodb__ConnectionString
          value: "mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary"
        - name: Mongodb__DatabaseName
          value: "sentinel"
        - name: Mongodb__CollectionName
          value: "product"
        - name: Mongodb__IdField
          value: "Id"
        - name: SentinelConnection
          value: "Server=sentinel-sql-db;Database=sentinel;User Id=sa;Password=Sentinel2018;"   
#---

apiVersion: v1
kind: Service
metadata:
  name: sentinel-web-api-product
  labels:
    app: sentinel-web-api-product
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: sentinel-web-api-product

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-web-api-product
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-web-api-product
    spec:
      containers:
      - name: sentinel-web-api-product
        image: mmercan/sentinel-web-api-product
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: RedisConnection
          value: "sentinel-db-redis:6379,defaultDatabase=2,password=yourpassword"
        - name: Mongodb__ConnectionString
          value: "mongodb://root:hbMnztmZ4w9JJTGZ@sentinel-db-mongodb:27017/admin?readPreference=primary"
        - name: Mongodb__DatabaseName
          value: "sentinel"
        - name: Mongodb__CollectionName
          value: "product"
        - name: Mongodb__IdField
          value: "Id"
        - name: SentinelConnection
          value: "Server=sentinel-sql-db;Database=sentinel;User Id=sa;Password=Sentinel2018;"

apiVersion: v1
kind: Service
metadata:
  name: sentinel-db-redis
  labels:
    app: sentinel-db-redis
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: sentinel-db-redis

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sentinel-db-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sentinel-db-redis
    spec:
      containers:
      - name: sentinel-db-redis
        image: mmercan/sentinel-db-redis
        ports:
        - containerPort: 6379    



# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sentinel-sql-db-data-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#    requests:
#     storage: 5Gi

# kind: Secret
# apiVersion: v1
# metadata:
#   name: sentinel-sql-db-secret
#   namespace: default
# data:
#   # Password is P@ssword1$ so update it with password of your choice  
#   SA_PASSWORD: UEBzc3dvcmQxJA==
# type: Opaque

# apiVersion: v1
# kind: Service
# metadata:
#   name: sentinel-sql-db-service
# spec:
#   selector:
#     app: sentinel-sql-db
#   ports:
#     - protocol: TCP
#       port: 1433
#       targetPort: 1433
#   type: ClusterIP

# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: sentinel-sql-db-deployment
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: sentinel-sql-db
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#       - name: mssql
#         image: microsoft/mssql-server-linux
#         ports:
#         - containerPort: 1433
#         env:
#         - name: ACCEPT_EULA
#           value: "Y"
#         - name: SA_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: sentinel-sql-db-secret
#               key: SA_PASSWORD
#         volumeMounts:
#         - name: mssql-persistent-storage
#           mountPath: /var/opt/mssql
#       volumes:
#       - name: mssql-persistent-storage
#         persistentVolumeClaim:
#           claimName: sentinel-sql-db-data-claim