FROM docker.elastic.co/logstash/logstash-oss:6.4.3
EXPOSE 5044 9600
ENV LS_JAVA_OPTS="-Xmx256m -Xms256m"



COPY ./data/cars.csv /usr/share/logstash/data
COPY ./pipeline/logstash-car.conf /usr/share/logstash/pipeline

#CMD [ "logstash-plugin", "install", "logstash-output-gelf",  "; /usr/local/bin/docker-entrypoint"]
WORKDIR /usr/local/bin/
RUN logstash-plugin install logstash-output-gelf
RUN logstash-plugin install logstash-input-azure_event_hubs
RUN logstash-plugin list