FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS develop
# RUN apt-get update && apt-get install bash
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.Web.Api.Product
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.Web.Api.Product/Sentinel.Web.Api.Product.csproj Sentinel.Web.Api.Product/
RUN dotnet restore Sentinel.Web.Api.Product/Sentinel.Web.Api.Product.csproj
COPY . .
WORKDIR /src/Sentinel.Web.Api.Product
RUN dotnet build Sentinel.Web.Api.Product.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.Web.Api.Product.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.Web.Api.Product.dll"]
