version: "3.4"

services:
  sentinel-ui-healthmonitoring-test:
    image: mmercan/sentinel-ui-healthmonitoring-test:${TAGVersion}-test-linux
    build:
      target: test
      context: ../
      dockerfile: Sentinel.UI.HealthMonitoring/dockerfile-test
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Production
    #   - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
