{{- $name := include "Sentinel.Api.HealthMonitoring.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
{{- $secretname := printf "%s-%s" $name "secret" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "Sentinel.Api.HealthMonitoring.fullname" . }}
  labels:
    {{- include "Sentinel.Api.HealthMonitoring.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Api.HealthMonitoring.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "Sentinel.Api.HealthMonitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Sentinel.Api.HealthMonitoring.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "Sentinel.Api.HealthMonitoring.annotations" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "Sentinel.Api.HealthMonitoring.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http 
          envFrom:
            - configMapRef:
                name: {{ $cfgname }}
            - secretRef:
                name: {{ $secretname }}
          env:
          {{- if .Values.env.values -}}
          {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end -}}
          {{- end -}}

