apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Api.HealthMonitoring.fullname" . }}
  labels:
    {{- include "Sentinel.Api.HealthMonitoring.labels" . | nindent 4 }}
  annotations:
    {{- include "Sentinel.Api.HealthMonitoring.service.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "Sentinel.Api.HealthMonitoring.selectorLabels" . | nindent 4 }}
