apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret-kibana-prod
spec:
  secretName: tls-secret-kibana-prod
  dnsNames:
  - kibana.myrcan.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kibana.myrcan.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-admin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: “true”
spec:
  tls:
  - hosts:
    - kibana.myrcan.com
    secretName: tls-secret-kibana-prod
  rules:
  - host: kibana.myrcan.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sentinel-elk-kibana
          servicePort: 80