apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret-ui-admin-prod
spec:
  secretName: tls-secret-ui-admin-prod
  dnsNames:
  - admin.myrcan.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - admin.myrcan.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sentinel-admin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: "gzip on;"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - admin.myrcan.com
    secretName: tls-secret-ui-admin-prod
  rules:
  - host: admin.myrcan.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sentinel-ui-admin
          servicePort: 80
      - path: /auth
        backend:
          serviceName: sentinel-ui-sts-service
          servicePort: 80