
FROM mmercan/sentinel-sonarqube-dotnet22-sdk AS test
# ENV SONAR_HOST http://sonar.myrcan.com
ENV PROJECT=Sentinel.Handler.Comms
ENV VERSION=1.0
ENV SONARKEY=fbf6f7c2fed68cbdc15fa82e269f973930831e3b
WORKDIR /src
COPY Sentinel.Handler.Comms/Sentinel.Handler.Comms.csproj Sentinel.Handler.Comms/
RUN dotnet restore Sentinel.Handler.Comms/Sentinel.Handler.Comms.csproj
COPY . .
RUN dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONARKEY  /d:sonar.cs.opencover.reportsPaths="/TestResults/coverage.opencover.xml" /d:sonar.exclusions="**bootstrap.css, **bootstrap.js" /d:sonar.coverage.exclusions="**Tests*.cs"
RUN dotnet build ./Sentinel.Handler.Comms/Sentinel.Handler.Comms.sln
RUN dotnet test ./Sentinel.Handler.Comms/Sentinel.Handler.Comms.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=/TestResults/
RUN dotnet build-server shutdown
RUN dotnet sonarscanner end /d:sonar.login=$SONARKEY

