FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS develop
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.Api.Member
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.Api.Member/Sentinel.Api.Member.csproj Sentinel.Api.Member/
RUN dotnet restore Sentinel.Api.Member/Sentinel.Api.Member.csproj
COPY . .
WORKDIR /src/Sentinel.Api.Member
RUN dotnet build Sentinel.Api.Member.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.Api.Member.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.Api.Member.dll"]
