FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS develop
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /src/Sentinel.Api.Scheduler
EXPOSE 80

FROM develop AS build
WORKDIR /src
COPY Sentinel.Api.Scheduler/Sentinel.Api.Scheduler.csproj Sentinel.Api.Scheduler/
RUN dotnet restore Sentinel.Api.Scheduler/Sentinel.Api.Scheduler.csproj
COPY . .
WORKDIR /src/Sentinel.Api.Scheduler
RUN dotnet build Sentinel.Api.Scheduler.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sentinel.Api.Scheduler.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sentinel.Api.Scheduler.dll"]
