    version: '3.4'

    services:
      sentinel-api-scheduler:      
        image: mmercan/sentinel-api-scheduler:${TAGVersion}-prod-linux
        build:
          target: final
          context: ../
          dockerfile: Sentinel.Api.Scheduler/dockerfile-linux
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - DOTNET_USE_POLLING_FILE_WATCHER=1
        # ports:
        #   - "5005:80"
