{{- if .Values.ingress.enabled -}}
{{- $fullName := include "Sentinel.Api.Comms.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret-comms-helm-prod
spec:
  secretName: tls-secret-comms-helm-prod
  dnsNames:
  - comms-helm.api.myrcan.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - comms-helm.api.myrcan.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
    helm.sh/chart: {{ include "Sentinel.Api.Comms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: tls-secret-comms-helm-prod
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "Sentinel.Api.Comms.fullname" . }}
          servicePort: 80