apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "Sentinel.Api.Comms.fullname" . }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "Sentinel.Api.Comms.name" . }}
    helm.sh/chart: {{ include "Sentinel.Api.Comms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: "Opaque"
data:
  RedisConnection: {{ default "" .Values.secrets.RedisConnection | b64enc | quote }}
  SentinelConnection: {{ default "" .Values.secrets.SentinelConnection | b64enc | quote }}