apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sentinel.Util.Mailhog.fullname" . }}
  labels:
    {{- include "Sentinel.Util.Mailhog.labels" . | nindent 4 }}
  annotations:
    healthcheck/crontab: '0 * * * *'
    healthcheck/isaliveandwell: /
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "Sentinel.Util.Mailhog.selectorLabels" . | nindent 4 }}