apiVersion: v1
kind: Service
metadata:
  name: sentinel-ui-healthmonitoring
  labels:
    app: sentinel-ui-healthmonitoring
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: sentinel-ui-healthmonitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-ui-healthmonitoring
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: sentinel-ui-healthmonitoring
    spec:
      containers:
      - name:  sentinel-ui-ahealthmonitoringdmin
        image: mmercan/sentinel-ui-healthmonitoring:__imageversion__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: imageversion
          value: "__imageversion__"
